# CI de Nível 01 - Disparo automático em períodos definidos

# Nome que vai aparecer nas opções
name: 'Execução Agendada'

# Triggers ou gatilhos de execução
# Gatilho de execução agendada = schedule
on:
  schedule:
     - cron: '0 8 * * 1'   

jobs:
  # Descrição do job
  e2e-tests:
    # Máquina que o job vai executar
    runs-on: ['ubuntu-latest']
    # Passo a passo das ações do job
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*
      - name: Instalando dependências (yarn global)
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Instalando Playwright
        run: yarn playwright install
      - name: Testes E2E (end-to-end)
        run: yarn run e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled()}}
        with:
           name: relatorio-de-testes
           path: ./playwright-report   